### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [shand26/intro-data-capstone-biodiversity#4]
(Exceeds Expectations)

Well done on this project! Good job on all the calculations as well as data visualizations. In addition, your presentation slides were very clear and efficient in presenting your findings. Great that you are not just showing the results of your calculations but also interpreting what it signifies! And great attention to detail as well, including using color/bolding text to highlight main points in your slides!

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by shand26** [comment]
Thanks for the great Feedback, I really enjoyed the course!
